# Generated by Django 5.0 on 2024-02-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_posted',
            new_name='date',
        ),
    ]
