# Generated by Django 5.0 on 2024-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, max_length=300, null=True, upload_to='news/'),
        ),
    ]
